### ISSUE TITLE
"ShareFile: '<filename>' is not a file, please select a file." in fman 1.0.0 on Windows.

### ISSUE THREAD

**Issue by IgorKrupenja** [umahmood/ShareFile#1]
Setup:
fman v1.0.0 running as Administrator on Windows 10 Home x64, build 16299.371.

Steps:
1. Install ShareFile plugin using Install Plugin command.
2. Place the cursor over the file you want to share.
3. Press Shift + s.

Result:
Status bar displays an error: "ShareFile: '<filename>' is not a file, please select a file.". File is not uploaded.

**Comment by sosloow** [comment]
I'm getting the same error on OSX.

**Comment by umahmood** [comment]
Hello,

Thank you for reporting the issue. 

I believe I have fixed the issue, can you please give it another go?  You will need to update the plugin. It's probably best to remove the plugin (cmd+shift+p -> search 'remove plugin'), and then re-installing it using fman (cmd+shift+p -> search 'install plugin'). 

I do not have access to a Windows machine but it should work. 

Tested on:
- macOS 10.13.4 
- fman 1.0.4

Thanks.

**Comment by sosloow** [comment]
Hi, I ran it on the same mac 10.13.4 & fman 1.0.4 and got this when tried to upload the file
```
Plugin 'ShareFile' raised an error.

Traceback (most recent call last):
  File "fman/impl/excepthook.py", line 86, in run_with_except_hook
  File "/Users/s.shilin/Library/Application Support/fman/Plugins/Third-party/ShareFile/share_file/__init__.py", line 84, in run
    with request.urlopen(req, timeout=10) as resp:
  File "urllib/request.py", line 163, in urlopen
  File "urllib/request.py", line 466, in open
  File "urllib/request.py", line 484, in _open
  File "urllib/request.py", line 444, in _call_chain
  File "urllib/request.py", line 1297, in https_open
  File "urllib/request.py", line 1254, in do_open
  File "http/client.py", line 1107, in request
  File "http/client.py", line 1142, in _send_request
  File "http/client.py", line 984, in putrequest
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-8: ordinal not in range(128)
```
It happened when I tried to upload a file with cyrillic characters in the filename.

When I tried to share another file I've got

```
[Errno 32] Broken pipe
```

**Comment by umahmood** [comment]
Hello @sosloow 

I believe I have fixed the bug, can you update the plugin and give it another go.

Thank you,

**Comment by sosloow** [comment]
It works now, even with cyrillic filenames. Thanks.
